# --- PLEASE EDIT THE LINES BELOW CORRECTLY ---
# SOME DESCRIPTIVE TITLE.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2013-03-22 11:22+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language-Code: en\n"
"Language-Name: English\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: ftw.geo\n"

#. Default: "More than one location found, chose first match \"${place}\". Please check that coordinates are correct."
#: ./ftw/geo/handlers.py:44
msgid "msg_multiple_matches"
msgstr ""

#. Default: "Geocoding failed because of a network error."
#: ./ftw/geo/handlers.py:68
msgid "msg_network_error"
msgstr ""

#. Default: "Couldn't find a suitable match for location \"${location}\". Please use the \"coordinates\" tab to manually set the correct map loaction."
#: ./ftw/geo/handlers.py:52
msgid "msg_no_match"
msgstr ""

#. Default: "Geocoding failed because daily query limit has been exceeded."
#: ./ftw/geo/handlers.py:61
msgid "msg_too_many_queries"
msgstr ""

#. Default: "Geocoding failed because of an error: ${ecxeption}"
#: ./ftw/geo/handlers.py:76
msgid "msg_unhandled_exception"
msgstr ""

